### PR TITLE
Initialize Go dependencies

### PR DESCRIPTION
**Pull request by crackcomm**
```console
$ # To populate vendor directory
$ dep ensure
$ # To test the package
$ go test -v github.com/senior7515/smf/src/go-smf
```

### CODE REVIEW

**Comment by senior7515** [comment]
Thanks giving this a shot now. I will squash and clean too.

**Comment by senior7515** [comment]
@crackcomm  i'm getting this issue. 

```
 agallego@mountdoom  ~/workspace/smf   feature/go ●  which dep  
~/.golang/bin/dep
 agallego@mountdoom  ~/workspace/smf   feature/go ●  dep ensure
/home/agallego/workspace/smf is not within a known GOPATH/src

```

will investigate further.

**Comment by senior7515** [comment]
```
#!/bin/bash
set -evx
git_root=$(git rev-parse --show-toplevel)
export GOPATH=${git_root}/build
mkdir -p $GOPATH
go get -u github.com/golang/dep/cmd/dep
mkdir -p ${GOPATH}/src
ln -s ${git_root} ${GOPATH}/src/smf
export PATH=$GOPATH/bin:$PATH

```

this seems to have worked around the issue.

**Comment by crackcomm** [comment]
go would expect repository to be located in `$GOPATH/src/github.com/senior7515/smf`

**Pull request merged**
