### PR TITLE
build: change directory name to target

### PR DESCRIPTION
**Pull request by crackcomm**
Bazel already reserved this file name.

### CODE REVIEW

**Comment by senior7515** [comment]
I'm going to create an organization. 

then have `smf/core`  and `smf/rust` and `smf/go`

**Comment by crackcomm** [comment]
The problem is not the bazel but cmake build. I have to move BUILD file
everytime to build smf with ./tools/build.sh

pon., 22 paź 2018 o 01:22 Alexander Gallego <notifications@github.com>
napisał(a):

**Comment by crackcomm** [comment]
hahaha @senior7515 epic

**Comment by senior7515** [comment]
sigh github db is really messed up.

**Comment by senior7515** [comment]
btw, the compiler should work on windows too. The seastar client code will not work on windows, but the compiler and code generator should work on windows just fine.

**Comment by crackcomm** [comment]
it does you just have to move `BUILD` file everytime 😂

**Comment by crackcomm** [comment]
every
single
time

**Comment by senior7515** [comment]
that's weird. maybe your filesystem is case insensitive. 

on my TODO list. I'll fix it this weekend tho. 

i think having 2 build systems is bad. 

I was hoping to unify, but we have clients depending on CMake and go has it's own build system, so, in retrospect, i think I should have kept multiple repos under a single org. 

I'll clean it up this weekend. in the mean time, just fork master and remove it on your branch.

**Comment by crackcomm** [comment]
that's cool, I'm using CMake too and it's more popular/accelerating tool than others, easier to find resources and integrate other projects at least from my experience

I will close the PR, thanks.

**Comment by crackcomm** [comment]
By the way, you will want the whole distribution for C-bindings. Languages like Rust which uses crates.io, node.js which uses npm and Go which uses git, see gopkg.in

**Comment by noahdesu** [comment]
long live cmake

**Pull request closed without merging**
