### PR TITLE
Feature/golang support

### PR DESCRIPTION
**Pull request by senior7515**

### CODE REVIEW

**Comment by senior7515** [comment]
@noahdesu  - almost there w/ cmake.

**Comment by senior7515** [comment]
@crackcomm  we are enlisting @noahdesu 's cmake help to finish the last few things. I managed to get a gosmf.a library built correctly under gopath. 

but the builds are flaky. 

@noahdesu  is our resident cmake expert! Once we get that, we'll add his help to also get the demo apps wrokgin w/ cmake.

**Comment by noahdesu** [comment]
Hey ya'll... Go support is going to be awesome :)

I took at a quick look at this PR. It doesn't look like there are any C bindings, and so this is a pure-Go implementation of the protocol. Is that correct?

**Comment by senior7515** [comment]
@noahdesu  - right, i added go_generator.h,cc for apps which actually generates pure go - no c++ binding. I imagine the java will be the same.

**Comment by senior7515** [comment]
@noahdesu  - basically these https://github.com/senior7515/smf/blob/master/src/smfc/go_generator.cc

and this 

https://github.com/senior7515/smf/blob/master/CMake/smf.cmake#L17-L22

for generating the go for the /demo_apps though I haven't gotten that far yet!

**Comment by noahdesu** [comment]
Ahh, OK the contents of this patch makes a lot more sense now. So the architecture is very similar to the C++ code generation, just minus the linking. So the dependencies are really just against the generator. In that case, we can create a cmake target like the smf generator target. And that is probably what you are already doing! :) Would it be helpful at this point to pull down this PR and test it out? Sounds like there are just some rough edges?

Having the language generators in smf makes sense. Are you planning to keep all the language implementations in here too as opposed to smf-go, smf-java being separate projects?

**Comment by senior7515** [comment]
Yeah, basically, there are just a couple of rough edges w/ my cmake-foo, but otherwise, this should just work! (famous last words) - @crackcomm  did most of the work - I've just been putting it together and merging it here on this repo. 

We are going to merge them here on this repo. 

Because we do a lot via code generation the code binding per language is actually really small! 
if it grows large we should split and make smf an organization, but for simplicity let's keep them here.

**Comment by noahdesu** [comment]
Sounds good. I'll take this for a spin.

**Pull request merged**
