### PR TITLE
More submod fixes

### PR DESCRIPTION
**Pull request by noahdesu**
1. This adds useful options for consumers of smf to control what is built (e.g. smf_build_{tests, programs, etc..}).

2. disables lots of unused bits in dependencies that are built from scratch

3. builds a single smf library, rather than several libraries like `smf_utils` etc... this may help build times too as there isn't intermediate linking, plus it simplifies things for users of smf.

Note this branch was working, but after a rebase on master it has same issues showing up in travis, but it sounds like that will resolve soon.

### CODE REVIEW

**Comment by noahdesu** [comment]
also bumped the version of hdr histogram to include changes i merged upstreamed for disabling tests and shared libraries from being built.

**Comment by senior7515** [comment]
testing this now and ./debug works but release fails to include seastar. 

```
../src/integration_tests/histograms/main.cc:4:10: fatal error: core/app-template.hh: No such file or directory                                                                                                                                                
 #include <core/app-template.hh>                                                                                                                                                                                                                                        ^~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                              
compilation terminated.                 
```

**Comment by senior7515** [comment]
though i see the right seastar dir set.

**Comment by senior7515** [comment]
ah it's only for tests, if I do release quick. it works.

**Comment by noahdesu** [comment]
try this out

https://github.com/senior7515/smf/pull/213

**Comment by noahdesu** [comment]
i was testing with tests and programs disabled my bad

**Pull request merged**
