### PR TITLE
install-deps.sh: recognize linuxmint

### PR DESCRIPTION
**Pull request by crackcomm**
Script works on Linux Mint fine, we can include it too.

### CODE REVIEW

**Comment by senior7515** [comment]
LGTM.

**Comment by senior7515** [comment]
also, @crackcomm  - thank you for your first PR! w00t. Hope it was easy to contribute. Let me know if you need help getting started or have any issues getting up and running.

**Comment by crackcomm** [comment]
I actually do, should I build the smf with seastar on master? here's my `./debug` [log](https://gist.github.com/crackcomm/05c30f41ab6d5f49ccfab2878728ad6a). `g++ (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04) 6.3.0 20170519`.

**Comment by senior7515** [comment]
what compiler are you using ? 

I think it's a compiler bug.

**Comment by senior7515** [comment]
I'm using this

```
 agallego@mountdoom  ~/workspace/smf   master ●  gcc --version    
gcc (GCC) 7.3.1 20180130 (Red Hat 7.3.1-2)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


```

**Comment by senior7515** [comment]
I don't think is flatc... it looks like the compiler can't deduce a `this->hist_->automeasure()` which is the thing that tracks latency distributions. 

```
../src/rpc/rpc_server.cc:161:22: error: cannot call member function ‘seastar::future<> smf::rpc_server::dispatch_rpc(seastar::lw_shared_ptr<smf::rpc_server_connection>, smf::rpc_recv_context&&)’ without object
                     .finally([m = hist_->auto_measure()]{});
```

If you post your compiler version, i can help you get up and running.

**Comment by senior7515** [comment]
can you file a separate issue for this, and we can track it there. Thanks!

**Pull request merged**
